config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    # все маршруты
    root "posts#index"
    resources :posts
    resources :pictures, only: [ :create, :destroy ]
    resources :categories
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :post
  validates :name, presence: true
end

app/models/picture.rb
class Picture < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :category
    mount_uploader :image, ImageUploader
    validates :title, :summary, :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true
  add_flash_types :success, :danger
  before_action :set_locale

  private

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options(options = {})
    { locale: I18n.locale }.merge options
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  def show

  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path success: 'Категория успешно создана'
    else
      flash.now[:danger] = 'Категория не создана'
      render :new
    end
  end

  def edit
  end

  def update
    if @category.update_attributes(category_params)
      redirect_to @category, success: 'Категория успешно обновлена'
    else
      flash.now[:danger] = 'Категория не обновлена'
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_path, success: 'Категория успешно удалена'
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end


end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController

  def create
    @picture = Picture.new(image_params)
    if @picture.save
      # byebug
      respond_to do |format|
        format.json { render :json => {url: @picture.image, picture_id: @picture.id } }
      end
    end
  end

  def destroy
    picture = Picture.find(params[:id])
    picture.destroy
    respond_to do |format|
      format.json { render json: {status: :ok } }
    end
  end

  def image_params
    params.require(:picture).permit(:image)
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.paginate(:page => params[:page], :per_page => 5)

  end

  def show
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.create(post_params)
    if @post.save
      redirect_to @post, success: 'Статья успешно создана'
    else
      flash.now[:danger] =  'Статья не создана'
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update_attributes(post_params)
      redirect_to @post, success: 'Статья успешно обновлена'
    else
      flash.now[:danger] = 'Статья не обновлена'
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path, success: 'Статья успешно удалена'
  end

  private

  def set_post
    @post = Post.find(params[:id ])
  end

  def post_params
    params.require(:post).permit(:title, :summary, :body, :category_id, :image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/_form.html.erb
<% if @category.errors.any? %>
  <div class="alert alert-danger">
    <h5><%= t('common.errors') %></h5>
    <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @category do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.submit I18n.t('.categories.form.submit', action: @category.new_record? ? I18n.t('categories.form.create') : I18n.t('categories.form.edit')), class: 'btn btn-primary' %>
    <%= link_to I18n.t('common.back'), :back, class: 'btn btn-outline-secondary' %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1><%= I18n.t('.categories.edit.title') %></h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<h3><%= I18n.t('.categories.index.title') %></h3>

<div class="buttons_panel">
  <%= link_to 'Новая категория', new_category_path, class: 'btn btn-outline-primary btn-sm' %>
</div>

<section id="categories">
  <table class="table">
    <thead>
    <tr>
      <th>#</th>
      <th>Название</th>
      <th></th>
    </tr>
    </thead>
    <tbody>
    <% @categories.each_with_index do |category, index| %>
        <tr>
          <td><%= index %></td>
          <td><%= category.name %></td>
          <td>
            <%= link_to 'Изменить', edit_category_path(category), class: 'btn btn-outline-primary btn-sm' %>
            <%= link_to 'Удалить', category_path(category), method: :delete, data: {confirm: 'Вы уверены' }, class: 'btn btn-outline-danger btn-sm' %>
          </td>
        </tr>
        <% end %>
    </tbody>
  </table>
</section>

app/views/categories/new.html.erb
<h2><%= I18n.t('.posts.new.title') %></h2>

<%= render "form" %>

app/views/categories/show.html.erb
<article class="post">
  <section class="post-head">
    <h1><%= @post.title %></h1>
    <small>
      <time> <%= @post.created_at.to_date.strftime("%b %B, %Y") %> </time>
      |
      <%= link_to I18n.t('.posts.show.edit'), edit_post_path(@post) %>
      |
      <%= link_to I18n.t('.posts.show.delete'), post_path(@post), method: :delete, data: {confirm: 'Вы уверены?'} %>

    </small>
  </section>

  <section class="post-body">
    <%= image_tag @post.image, class: 'img-show' if @post.image? %>
    <%= @post.body.html_safe %>
  </section>
</article>

<%= render 'disqus' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogRailsHome</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">
    <nav class="navbar navbar-light bg-light">
      <ul class="nav menu navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href=" <%= posts_path %> "><%= I18n.t('.layouts.application.articles') %></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#"><%= I18n.t('.layouts.application.contacts') %></a>
        </li>
        <li>
          <%= link_to 'En', locale: :en %>
        </li>
        <li>
          <%= link_to 'Рус', locale: :ru %>
        </li>
      </ul>

      <%= link_to I18n.t('.layouts.application.new'), new_post_path, class: 'btn btn-outline-primary pull-xs-right' %>

    </nav>
  </div>

  <div class="container main">
    <div class="row">
      <div class="col-md-12">
        <% flash.each do |name, message| %>
        <div class="alert alert-<%=name%>">
          <%= message %>
        </div>
            <% end %>
      </div>
    </div>
    <%= yield %>
  </div>

  </body>
</html>

app/views/posts/_disqus.html.erb
<div id="disqus_thread"></div>
<script>

    /**
     *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
     *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
    /*
    var disqus_config = function () {
    this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
    this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
    };
    */
    var disqus_config = function () {
        this.page.url = 'http://localhost.com<%= request.original_fullpath %> ' ;  // Replace PAGE_URL with your page's canonical URL variable
        this.page.identifier = <%= @post.id %>; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
    };
    (function() { // DON'T EDIT BELOW THIS LINE
        var d = document, s = d.createElement('script');
        s.src = 'https://blog-rails-home.disqus.com/embed.js';
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

app/views/posts/_form.html.erb
<% if @post.errors.any? %>
    <div class="alert alert-danger">
      <h5><%= t('common.errors') %></h5>
      <ul>
        <% @post.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
      </ul>
    </div>
<% end %>

<%= form_for @post, html: {multipart: true} do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :summary %>
      <%= f.text_area :summary, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :body %>
      <%= f.trix_editor :body, class: 'editor' %>
    </div>
    <div class="form-group">
      <%= f.label :category_id %>
      <%= f.collection_select  :category_id, Category.order(:name), :id, :name, {include_blank: true}, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.file_field :image %>
    </div>

    <div class="form-group">
      <%= f.submit I18n.t('.posts.form.submit', action: @post.new_record? ? I18n.t('posts.form.create') : I18n.t('posts.form.edit')), class: 'btn btn-primary' %>
      <%= link_to I18n.t('common.back'), :back, class: 'btn btn-outline-secondary' %>
    </div>
<% end %>

app/views/posts/_post.html.erb
<article class="post">
  <section class="post-head">
    <h2><%= link_to post.title, post_path(post) %></h2>
    <small>
      <time> <%= post.created_at.to_date.strftime("%d %B, %Y") %> </time>
      <% if post.category.present? %>
        |
        <%= link_to post.category.name, post.category %>
      <% end %>
      |
      <%= link_to I18n.t('.posts.post.edit'), edit_post_path(post) %>
      |
      <%= link_to I18n.t('.posts.post.delete'), post_path(post), method: :delete, data: {confirm: 'Вы уверены?'} %>

    </small>
  </section>

  <section class="post-summary clearfix ">
    <%= image_tag post.image, class: 'img-thumbnail thumb' if post.image? %>
    <%= post.summary %>

  </section>
</article>

app/views/posts/edit.html.erb
<h1><%= I18n.t('.posts.edit.title') %></h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<h3><%= I18n.t('.posts.index.title') %></h3>

<%= render @posts %>

<%= will_paginate @posts, renderer: BootstrapPaginationHelper::LinkRenderer %>

app/views/posts/show.html.erb
<article class="post">
  <section class="post-head">
    <h1><%= @post.title %></h1>
    <small>
      <time> <%= @post.created_at.to_date.strftime("%b %B, %Y") %> </time>
      <% if @post.category.present? %>
          |
          <%= link_to @post.category.name, @post.category %>
      <% end %>
      |
      <%= link_to I18n.t('.posts.show.edit'), edit_post_path(@post) %>
      |
      <%= link_to I18n.t('.posts.show.delete'), post_path(@post), method: :delete, data: {confirm: 'Вы уверены?'} %>

    </small>
  </section>

  <section class="post-body">
    <%= image_tag @post.image, class: 'img-show' if @post.image? %>
    <%= @post.body.html_safe %>
  </section>
</article>

<%= render 'disqus' %>